services:

  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ToDolist:/code
    environment: # os.environ
      - DB_HOST=db
      - DB_NAME=todolist
      - DB_USER=postgres
      - DB_PASS=05081992
    
    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=05081992
    
  redis:
    image: redis:7.0.5-alpine
    hostname: redis