services:

  web-app:
    build: 
      context: .
    volumes:
      - .:/todolist
    environment: # os.environ
      - DB_HOST=db
      - DB_NAME=todolist
      - DB_USER=postgres
      - DB_PASS=05081992
    
    command: ["./wait-for-it.sh", "db:5432", "--",
              "uwsgi", "--ini", "/todolist/config/uwsgi/uwsgi.ini"]

    depends_on:
      - db
      - redis

  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=05081992
    volumes:
      - db_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7.0.5-alpine
    hostname: redis
  
  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/todolist
    ports:
      - "80:80"

volumes:
  db_data:
