# Generated by Django 4.1.13 on 2024-01-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('To-Do', 'Не сделано'), ('Completed', 'Сделано')], default='todo', max_length=20),
        ),
    ]
